package graWSwingu;

import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class Gra extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form pd2_5
     */
    public Gra() {
        initComponents();
        Wilk_dwa.setEnabled(false);
        Koza_dwa.setEnabled(false);
        Kapusta_dwa.setEnabled(false);
        Wyrzuc.setEnabled(false);
        Restart.setVisible(false);
        Przewoznik_wyspa_2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Wilk_jeden = new javax.swing.JButton();
        Koza_jeden = new javax.swing.JButton();
        Kapusta_jeden = new javax.swing.JButton();
        Plyn = new javax.swing.JButton();
        Wilk_dwa = new javax.swing.JButton();
        Koza_dwa = new javax.swing.JButton();
        Kapusta_dwa = new javax.swing.JButton();
        Wyrzuc = new javax.swing.JButton();
        Informacja = new javax.swing.JLabel();
        Wygrana_Przegrana = new javax.swing.JLabel();
        Przewoznik_wyspa_1 = new javax.swing.JLabel();
        Przewoznik_wyspa_2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Bool = new javax.swing.JTextField();
        Restart = new javax.swing.JButton();
        Numer_obiektu = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Wilk, koza, kapusta");

        Wilk_jeden.setText("Wilk");
        Wilk_jeden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Wilk_jedenActionPerformed(evt);
            }
        });

        Koza_jeden.setText("Koza");
        Koza_jeden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Koza_jedenActionPerformed(evt);
            }
        });

        Kapusta_jeden.setText("Kapusta");
        Kapusta_jeden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kapusta_jedenActionPerformed(evt);
            }
        });

        Plyn.setText("Płyń!");
        Plyn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlynActionPerformed(evt);
            }
        });

        Wilk_dwa.setText("Wilk");
        Wilk_dwa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Wilk_dwaActionPerformed(evt);
            }
        });

        Koza_dwa.setText("Koza");
        Koza_dwa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Koza_dwaActionPerformed(evt);
            }
        });

        Kapusta_dwa.setText("Kapusta");
        Kapusta_dwa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kapusta_dwaActionPerformed(evt);
            }
        });

        Wyrzuc.setText("Wyrzuć obiekt z łódki");
        Wyrzuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WyrzucActionPerformed(evt);
            }
        });

        Informacja.setText("Obecnie w łódce masz:");

        Przewoznik_wyspa_1.setText("Przewoźnik jest tutaj");

        Przewoznik_wyspa_2.setText("Przewoźnik jest tutaj");

        jLabel6.setText("Czy zdołasz rozwiązać starożytną łamigłówkę?");

        Bool.setText("true");

        Restart.setText("Spróbuj ponownie");
        Restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestartActionPerformed(evt);
            }
        });

        Numer_obiektu.setText("-1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Wilk_jeden, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Informacja, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Kapusta_jeden)
                                    .addComponent(Koza_jeden, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(135, 135, 135)
                                        .addComponent(Wyrzuc))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(153, 153, 153)
                                        .addComponent(Plyn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Przewoznik_wyspa_1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Wygrana_Przegrana, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Kapusta_dwa)
                            .addComponent(Wilk_dwa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Koza_dwa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Numer_obiektu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addComponent(Przewoznik_wyspa_2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Bool, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(Restart)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Numer_obiektu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Bool, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Informacja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Wilk_dwa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Wilk_jeden, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(Kapusta_dwa))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Koza_jeden)
                                    .addComponent(Koza_dwa))
                                .addGap(45, 45, 45)
                                .addComponent(Kapusta_jeden)))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Przewoznik_wyspa_1)
                            .addComponent(Przewoznik_wyspa_2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Plyn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(Wyrzuc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Restart)
                        .addGap(18, 18, 18)
                        .addComponent(Wygrana_Przegrana, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Wylaczanie_Guzikow(){
        Wilk_jeden.setEnabled(false);
        Koza_jeden.setEnabled(false);
        Kapusta_jeden.setEnabled(false);
        Wilk_dwa.setEnabled(false);
        Koza_dwa.setEnabled(false);
        Kapusta_dwa.setEnabled(false);
        Plyn.setEnabled(false);
        Wyrzuc.setEnabled(false);
    }
    private void Dzialanie(){
        Informacja.setText("Obecnie w łódce masz:");
        Bool.setText("true");
        Numer_obiektu.setText("-1");
        Wyrzuc.setEnabled(false);
        Sprawdzacz();
    }
    private void Sprawdzacz(){
        if(Wilk_dwa.isEnabled() == true && Koza_dwa.isEnabled() == true && Kapusta_dwa.isEnabled() == true){
            Wylaczanie_Guzikow();
            Wygrana_Przegrana.setText("Gratulacje! Rozwiązałeś/łaś zagadkę!");
            Restart.setVisible(true);
        }
        if((Wilk_jeden.isEnabled() == true && Koza_jeden.isEnabled() == true && Przewoznik_wyspa_2.isVisible() == true) || (Koza_jeden.isEnabled() == true && Kapusta_jeden.isEnabled() == true && Przewoznik_wyspa_2.isVisible() == true) || (Wilk_dwa.isEnabled() == true && Koza_dwa.isEnabled() == true && Przewoznik_wyspa_1.isVisible() == true) || (Koza_dwa.isEnabled() == true && Kapusta_dwa.isEnabled() == true && Przewoznik_wyspa_1.isVisible() == true)){
            Wylaczanie_Guzikow();
            Wygrana_Przegrana.setText("Przegrałeś/łaś! Spróbuj jeszcze raz!");
            Restart.setVisible(true);
        }
    }
    
    private void PlynActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlynActionPerformed
        if(Przewoznik_wyspa_1.getText().trim().length() > 0){
            Przewoznik_wyspa_1.setText("");
            Przewoznik_wyspa_1.setVisible(false);
            Przewoznik_wyspa_2.setVisible(true);
            Przewoznik_wyspa_2.setText("Przewoźnik jest tutaj");
        }
        else{
            Przewoznik_wyspa_2.setText("");
            Przewoznik_wyspa_2.setVisible(false);
            Przewoznik_wyspa_1.setVisible(true);
            Przewoznik_wyspa_1.setText("Przewoźnik jest tutaj");
        }
        Sprawdzacz();
    }//GEN-LAST:event_PlynActionPerformed

    private void Wilk_jedenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Wilk_jedenActionPerformed
        boolean bool = Boolean.valueOf(Bool.getText());
        if(bool && Przewoznik_wyspa_1.isVisible() == true){
            Wilk_jeden.setEnabled(false);
            Informacja.setText("Obecnie w łódce masz: wilka");
            Bool.setText("false");
            Numer_obiektu.setText("0");
            Wyrzuc.setEnabled(true);
        }
    }//GEN-LAST:event_Wilk_jedenActionPerformed

    private void Koza_jedenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Koza_jedenActionPerformed
        boolean bool = Boolean.valueOf(Bool.getText());
        if(bool && Przewoznik_wyspa_1.isVisible() == true){
            Koza_jeden.setEnabled(false);
            Informacja.setText("Obecnie w łódce masz: kozę");
            Bool.setText("false");
            Numer_obiektu.setText("1");
            Wyrzuc.setEnabled(true);
        }
    }//GEN-LAST:event_Koza_jedenActionPerformed

    private void Kapusta_jedenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kapusta_jedenActionPerformed
        boolean bool = Boolean.valueOf(Bool.getText());
        if(bool  && Przewoznik_wyspa_1.isVisible() == true){
            Kapusta_jeden.setEnabled(false);
            Informacja.setText("Obecnie w łódce masz: kapustę");
            Bool.setText("false");
            Numer_obiektu.setText("2");
            Wyrzuc.setEnabled(true);
        }
    }//GEN-LAST:event_Kapusta_jedenActionPerformed

    private void Wilk_dwaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Wilk_dwaActionPerformed
        boolean bool = Boolean.valueOf(Bool.getText());
        if(bool && Przewoznik_wyspa_2.isVisible() == true){
            Wilk_dwa.setEnabled(false);
            Informacja.setText("Obecnie w łódce masz: wilka");
            Bool.setText("false");
            Numer_obiektu.setText("0");
            Wyrzuc.setEnabled(true);
        }
    }//GEN-LAST:event_Wilk_dwaActionPerformed

    private void Koza_dwaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Koza_dwaActionPerformed
        boolean bool = Boolean.valueOf(Bool.getText());
        if(bool && Przewoznik_wyspa_2.isVisible() == true){
            Koza_dwa.setEnabled(false);
            Informacja.setText("Obecnie w łódce masz: kozę");
            Bool.setText("false");
            Numer_obiektu.setText("1");
            Wyrzuc.setEnabled(true);
        }
    }//GEN-LAST:event_Koza_dwaActionPerformed

    private void Kapusta_dwaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kapusta_dwaActionPerformed
        boolean bool = Boolean.valueOf(Bool.getText());
        if(bool && Przewoznik_wyspa_2.isVisible() == true){
            Kapusta_dwa.setEnabled(false);
            Informacja.setText("Obecnie w łódce masz: kapustę");
            Bool.setText("false");
            Numer_obiektu.setText("2");
            Wyrzuc.setEnabled(true);
        }
    }//GEN-LAST:event_Kapusta_dwaActionPerformed

    private void WyrzucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WyrzucActionPerformed
        if (Wilk_jeden.isEnabled() == false && Przewoznik_wyspa_1.isVisible() == true && Integer.parseInt(Numer_obiektu.getText()) == 0) {
            Wilk_jeden.setEnabled(true);
            Dzialanie();
        }
        if (Wilk_jeden.isEnabled() == false && Przewoznik_wyspa_2.isVisible() == true && Integer.parseInt(Numer_obiektu.getText()) == 0) {
            Wilk_dwa.setEnabled(true);
            Dzialanie();
        }
        if (Koza_jeden.isEnabled() == false && Przewoznik_wyspa_1.isVisible() == true && Integer.parseInt(Numer_obiektu.getText()) == 1) {
            Koza_jeden.setEnabled(true);
            Dzialanie();
        }  
        if (Koza_jeden.isEnabled() == false && Przewoznik_wyspa_2.isVisible() == true && Integer.parseInt(Numer_obiektu.getText()) == 1) {
            Koza_dwa.setEnabled(true);
            Dzialanie();
        }
        if (Kapusta_jeden.isEnabled() == false && Przewoznik_wyspa_1.isVisible() == true && Integer.parseInt(Numer_obiektu.getText()) == 2) {
            Kapusta_jeden.setEnabled(true);
            Dzialanie();
        }
        if (Kapusta_jeden.isEnabled() == false && Przewoznik_wyspa_2.isVisible() == true && Integer.parseInt(Numer_obiektu.getText()) == 2) {
            Kapusta_dwa.setEnabled(true);
            Dzialanie();
        }
    }//GEN-LAST:event_WyrzucActionPerformed

    private void RestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestartActionPerformed
        
        Wilk_jeden.setEnabled(true);
        Koza_jeden.setEnabled(true);
        Kapusta_jeden.setEnabled(true);
        Restart.setVisible(false);
        Informacja.setText("Obecnie w łódce masz:");
        Przewoznik_wyspa_1.setText("Przewoźnik jest tutaj");
        Przewoznik_wyspa_1.setVisible(true);
        Przewoznik_wyspa_2.setVisible(false);
        Wygrana_Przegrana.setText("");
        Bool.setText("true");
        Plyn.setEnabled(true);
    }//GEN-LAST:event_RestartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bool;
    private javax.swing.JLabel Informacja;
    private javax.swing.JButton Kapusta_dwa;
    private javax.swing.JButton Kapusta_jeden;
    private javax.swing.JButton Koza_dwa;
    private javax.swing.JButton Koza_jeden;
    private javax.swing.JLabel Numer_obiektu;
    private javax.swing.JButton Plyn;
    private javax.swing.JLabel Przewoznik_wyspa_1;
    private javax.swing.JLabel Przewoznik_wyspa_2;
    private javax.swing.JButton Restart;
    private javax.swing.JButton Wilk_dwa;
    private javax.swing.JButton Wilk_jeden;
    private javax.swing.JLabel Wygrana_Przegrana;
    private javax.swing.JButton Wyrzuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}